# Generated by Django 4.1.7 on 2023-02-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Инвентарь', 'verbose_name_plural': 'Инвентари'},
        ),
    ]
