# Generated by Django 4.1.7 on 2023-02-17 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_bot_id'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.player', verbose_name='Игрок'),
        ),
    ]
