# Generated by Django 4.1.7 on 2023-02-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bot_id',
            field=models.CharField(default='', max_length=150, verbose_name='ID в боте'),
        ),
    ]
