# Generated by Django 4.1.7 on 2023-02-17 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_player_bot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='miner', max_length=255, verbose_name='Шахтер')),
                ('income', models.IntegerField(verbose_name='Доход')),
            ],
        ),
        migrations.CreateModel(
            name='MinerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mined_amount', models.IntegerField(default=0, verbose_name='Добыто')),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miners.miner', verbose_name='Шахтер')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player', verbose_name='Игрок')),
            ],
        ),
    ]
